package services

import (
	"bytes"
	"encoding/json"
	"fmt"
	"net/http"
)

// TODO: correct BPM calculation
type SpotifyPlaylistResponse struct {
    ID          string `json:"id"`
    Name        string `json:"name"`
    Description string `json:"description"`
    Public      bool   `json:"public"`
    // Add other fields as necessary
}

type RecommendationResponse struct {
	Tracks []struct {
		ID    string `json:"id"`
		Name  string `json:"name"`
		Artists []struct {
			Name string `json:"name"`
		} `json:"artists"`
		ExternalURLs struct {
			Spotify string `json:"spotify"`
		} `json:"external_urls"`
	} `json:"tracks"`
}

// CreatePlaylist generates a Spotify playlist based on the user's input
func CreatePlaylist(accessToken, paceUnit string, paceInSeconds int, gender string, height float64, heightUnit string) (string, error) {
	// Convert height to centimeters if needed
	if heightUnit == "in" {
		height = height * 2.54
	}

	// Calculate the desired BPM based on pace and height
	pacePerKm := float64(paceInSeconds) / 60.0
	bpm := int(180.0 / pacePerKm)

	// Call Spotify API to create a playlist
	playlistID, err := createSpotifyPlaylist(accessToken)
	if err != nil {
		return "", err
	}

	// Get a seed song
	seed_song, err:= get_song(accessToken, "pop", bpm)

	// Return the Spotify playlist link
	return fmt.Sprintf("https://open.spotify.com/playlist/%s", playlistID), nil
}

// Helper function to interact with the Spotify API
func createSpotifyPlaylist(accessToken string) (string, error) {
    url := "https://api.spotify.com/v1/me/playlists"

    playlistData := map[string]interface{}{
        "name":        "Beatpace Running Playlist",
        "description": "A playlist generated by Beatpace to match your running pace",
        "public":      false,
    }

    jsonData, err := json.Marshal(playlistData)
    if err != nil {
        return "", fmt.Errorf("failed to marshal playlist data: %w", err)
    }

    req, err := http.NewRequest("POST", url, bytes.NewBuffer(jsonData))
    if err != nil {
        return "", fmt.Errorf("failed to create request: %w", err)
    }

    req.Header.Set("Content-Type", "application/json")
    req.Header.Set("Authorization", "Bearer "+accessToken)

    client := &http.Client{}
    resp, err := client.Do(req)
    if err != nil {
        return "", fmt.Errorf("failed to send request: %w", err)
    }
    defer resp.Body.Close()

    if resp.StatusCode != http.StatusCreated {
        return "", fmt.Errorf("failed to create playlist, status code: %d", resp.StatusCode)
    }

    var playlistResponse SpotifyPlaylistResponse
    if err := json.NewDecoder(resp.Body).Decode(&playlistResponse); err != nil {
        return "", fmt.Errorf("failed to parse response JSON: %w", err)
    }

    return playlistResponse.ID, nil
}

func get_song(accessToken, seed_genre string, bpm int) (string, error){
	url := fmt.Sprintf(
		"https://api.spotify.com/v1/recommendations?seed_genres=%s&target_tempo=%d", 
		seed_genre, bpm)

	req, err := http.NewRequest("GET", url, nil)
	
	if err != nil {
		return "", err
	}

	req.Header.Set("Authorization", "Bearer "+accessToken)

	client := &http.Client{}
	resp, err := client.Do(req)
	if err != nil {
		return "", err
	}

	defer resp.Body.Close()

	if resp.StatusCode != http.StatusOK {
		return "", fmt.Errorf("failed to get songs, status code: %d", resp.StatusCode)
	}

	var songsResponse RecommendationResponse
	err = json.NewDecoder(resp.Body).Decode(&songsResponse)

	if err != nil {
		return "", err
	}

	if len(songsResponse.Tracks) == 0 {
		return "", fmt.Errorf("no songs found")
	}

	return songsResponse.Tracks[0].ExternalURLs.Spotify, nil
}